/**
*   IF THERE IS A PROBLEM WITH THE PHYSICAL PART OF THE INSTALLATION
*   CHANGE THE SMS-ONLY CONST BELOW TO TRUE, WHICH WILL SEND GENERATED
*   PREDICTIONS TO MOBILE NUMBER
**/
const SMS_ONLY_MODE = false;

function isSmsOnlyMode() {
  return SMS_ONLY_MODE;
}

module.exports = isSmsOnlyMode;
